---
- hosts: galaxyservers
  become: true
  become_user: root
  roles:
    - ilifu-node-role

- hosts: dbservers
  become: true
  become_user: root
  pre_tasks:
    - name: Install Dependencies
      package:
        name: 'acl'
    - name: Create Apptainer Config Dir
      file: 
        path: /usr/local/etc/singularity
        state: directory
        mode: 0755
        owner: root
        group: root
    - name: Install Apptainer Config Files  # these are copied from Ilifu's /usr/local/etc/singularity
      copy:
        src: "singularity/{{ item }}"
        dest: /usr/local/etc/singularity
        mode: 0644
        owner: root
        group: root
      with_items:
        - singularity.conf
        - ecl.toml
        - capability.json
  roles:
    - galaxyproject.postgresql
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres

- hosts: galaxyservers
  become: true
  become_user: root
  vars_files:
    - group_vars/galaxyservers/secret.yml  
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['acl', 'bzip2', 'git', 'make', 'tar', 'python3-venv', 'python3-setuptools']
  roles:
    - galaxyproject.tusd  
    - galaxyproject.galaxy
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ galaxy_user_name }}"
    - galaxyproject.nginx
    