# Galaxy, Postgres, Nginx
# During development phase, this is hand-installed using git
# - src: https://github.com/pvanheus/ilifu-node-role
- src: galaxyproject.galaxy
  version: 0.10.14
- src: galaxyproject.nginx
  version: 0.7.1
- src: galaxyproject.postgresql
  version: 1.1.2
- src: galaxyproject.postgresql_objects
  version: 1.2.0
- src: galaxyproject.miniconda
  version: 0.3.1
- src: usegalaxy_eu.certbot
  version: 0.1.11
- galaxyproject.repos
- galaxyproject.slurm