global:
  default_inherits: default

tools:
  default:
    abstract: true
    cores: 1
    mem: cores * 4
    context:
      walltime: null
  .*repeatmasker.*:
    context:
      walltime: 168
    cores: 8
    mem: cores * 4
  .*repeatmodeler.*:
    context:
      walltime: 168
    cores: 8
    mem: cores * 4

destinations:
  local_env:
    runner: local_runner
    max_accepted_cores: 1
    params:
      tmp_dir: true
  singularity:
    runner: local_runner
    max_accepted_cores: 1
    params:
      singularity_enabled: true
      singularity_cmd: /software/common/singularity/3.11.3/bin/singularity      
    env:
      # Ensuring a consistent collation environment is good for reproducibility.
      LC_ALL: C
      # The cache directory holds the docker containers that get converted
      APPTAINER_CACHEDIR: /tmp/singularity
      # Singularity uses a temporary directory to build the squashfs filesystem
      APPTAINER_TMPDIR: /tmp
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/slurm/bin
      LD_LIBRARY_PATH: /opt/slurm/lib      
  slurm:
    inherits: singularity
    runner: slurm
    max_accepted_cores: 32
    max_accepted_mem: 256
    max_cores: 32
    max_mem: 256
    params:
      native_specification: --nodes=1 --ntasks=1 --cpus-per-task={cores} --mem={round(mem*1024)} {'--time=' + str(walltime) + ':00:00' if walltime else str(walltime)}
